name: CI-pipeline

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: List Current Folder1
      run: |
        pwd
        ls -la
        cd ..
        mv pyramid_blogr_build_test pyramid_blogr
        cd .. 
        mv pyramid_blogr_build_test pyramid_blogr
        cd pyramid_blogr
        cd pyramid_blogr
        pwd
        ls -la
        
 #   /home/runner/work/pyramid_blogr_build_test/pyramid_blogr_build_test 
      
 #   - name: Set up Python ${{ matrix.python-version }}
 #     uses: actions/setup-python@v3
      
    - name: Create a Python virtual environment
      working-directory: /home/runner/work/pyramid_blogr/pyramid_blogr
      run: python3 -m venv env
    - name: List Current Folder2
      run: ls -la
      
    - name: Upgrade packaging tools
      run: env/bin/pip install --upgrade pip setuptools
      
    - name: Install the project in editable mode with its testing requirements
      run: env/bin/pip install -e ".[testing]"
      
    # Initialize and upgrade the database using Alembic
    - name: Generate your first revision.
      run: env/bin/alembic -c development.ini revision --autogenerate -m "init"
    - name: Upgrade to that revision.
      run: env/bin/alembic -c development.ini upgrade head
      
    - name: Load default data into the database using a script.
      run: env/bin/initialize_pyramid_blogr_db development.ini
  
    - name: Run your project's tests. 
      run: env/bin/pytest
      
# Run your project.
#      run: env/bin/pserve development.ini   
 #     working-directoty: ./pyramid_blogr        
        
#    - name: Install Dependencies
 #     run: |
  #      python -m pip install --upgrade pip
   #     pip install -r requirements.txt
    #- name: Run Tests
     # run: |
      #  python setup.py test
