name: CI-pipeline

on:
  push:
    branches: [ "main" ]
    
jobs:
  build-and-test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: List Current Folder1
      run: |
        pwd
        ls -la
            
 #   - name: Set up Python ${{ matrix.python-version }}
 #     uses: actions/setup-python@v3
      
    - name: Create a Python virtual environment
      run: python3 -m venv env
    - name: List Current Folder2
      run: ls -la
      
    - name: Upgrade packaging tools and Install wheel
      run: |
         env/bin/pip install --upgrade pip setuptools
         pip install wheel
      
    - name: Install the project in editable mode with its testing requirements
      continue-on-error: true
      run: env/bin/pip install -e ".[testing]"
      
    # Initialize and upgrade the database using Alembic
    - name: Generate your first revision.
      continue-on-error: true
      run: env/bin/alembic -c development.ini revision --autogenerate -m "init"
    - name: Upgrade to that revision.
      continue-on-error: true
      run: env/bin/alembic -c development.ini upgrade head
      
    - name: Load default data into the database using a script.
      continue-on-error: true
      run: env/bin/initialize_pyramid_blogr_db development.ini
  
    - name: Run your project's tests. 
      continue-on-error: true
      run: env/bin/pytest
      
    - name: Run Tests
      continue-on-error: true
      run: |
        python setup.py test  
           
    - name: Run your project.
      run: env/bin/pserve development.ini 
